name: Build and Compress Skia

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        run: |
          git clone --recursive --branch main https://github.com/google/skia.git skia
        shell: pwsh

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Sync dependencies
        run: |
          cd skia
          python tools/git-sync-deps
        shell: pwsh

      - name: Generate cmake files
        run: |
          cd skia
          bin/gn gen out/config --ide=json --json-ide-script=../../gn/gn_to_cmake.py
        shell: pwsh

      - name: Remove existing zip file
        run: |
          if (Test-Path skia.zip) {
            Remove-Item skia.zip
          }
        shell: pwsh

      - name: Compress skia directory
        run: |
          Compress-Archive -Path skia -DestinationPath skia.zip
        shell: pwsh

      - name: Remove cloned repository
        run: |
          Remove-Item -Recurse -Force skia
        shell: pwsh

      - name: Commit and push compressed file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add skia.zip
          git commit -m "Add compressed skia artifact"
          git push
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.tk }}
