name: Build and Publish Windows Skia DLL with GN

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Skia repository
        uses: actions/checkout@v2
        with:
          repository: google/skia  # Skia仓库地址
          path: skia
          ref: main  # 指定分支

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Build Skia with GN
        run: |
          cd skia
          python tools/git-sync-deps
          bin/gn gen out/Release --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false"
          ninja -C out/Release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: skia-dll
          path: skia/out/Release/skia.dll

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: skia-dll
          path: skia/out/Release/skia.dll
          if-no-files-found: error

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: skia/out/Release/skia.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
