name: Build and Commit Skia DLL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true

      - name: Install dependencies
        run: |
          msys2 -c "pacman -S --noconfirm --needed base-devel mingw-w64-x86_64-toolchain"

      - name: Run build script
        run: ./build.sh

      - name: Commit and push skia.dll
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add skia/build/skia.dll
          git commit -m "Add skia.dll built by GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.tk }}
