name: Build and Publish Skia Binaries for Multiple Platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up dependencies
        run: |
          choco install git curl -y

      - name: Run build script for Windows
        run: |
          ./build.sh

      - name: Upload artifact for Windows
        uses: actions/upload-artifact@v2
        with:
          name: skia-binaries-windows
          path: dist/

  publish:
    needs: build-windows
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact for Windows
        uses: actions/download-artifact@v2
        with:
          name: skia-binaries-windows
          path: dist/

      - name: Publish DLL to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*.dll
        env:
          GITHUB_TOKEN: ${{ secrets.tk }}
