name: Build and Compress Skia

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: google/skia
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Download and install zstd
        run: |
          Invoke-WebRequest -Uri "https://github.com/facebook/zstd/releases/download/v1.5.5/zstd-v1.5.5-win64.zip" -OutFile zstd.zip
          Expand-Archive -Path zstd.zip -DestinationPath zstd
          $env:Path += ";${{ github.workspace }}\zstd\zstd-v1.5.5-win64"
        shell: pwsh

      - name: Sync dependencies
        run: |
          cd skia
          python tools/git-sync-deps
        shell: pwsh

      - name: Generate configuration
        run: |
          cd skia
          bin/gn gen out/config --ide=json --json-ide-script=../../gn/gn_to_cmake.py
        shell: pwsh

      - name: Remove existing zst file
        run: |
          if (Test-Path skia.tar.zst) {
            Remove-Item skia.tar.zst
          }
        shell: pwsh

      - name: Compress skia directory
        run: |
          Compress-Archive -Path skia -DestinationPath skia.zip
          zstd -19 skia.zip -o skia.tar.zst
        shell: pwsh

      - name: Remove cloned repository
        run: |
          Remove-Item -Recurse -Force skia
        shell: pwsh

      - name: Commit and push compressed file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add skia.tar.zst
          git commit -m "Add compressed skia artifact"
          git push
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.tk }}
