name: Build and Publish Windows Skia DLL with GN and Ninja

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Skia repository
        uses: actions/checkout@v2
        with:
          repository: google/skia  # Skia仓库地址
          path: skia
          ref: main  # 指定分支

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install GN
        run: |
          cd skia
          python tools/git-sync-deps
          mkdir -p third_party/externals/gn
          curl -L https://chrome-infra-packages.appspot.com/dl/gn/gn/windows-amd64/+/latest -o gn.zip
          unzip gn.zip -d third_party/externals/gn
          cp third_party/externals/gn/gn.exe C:/Windows/System32/

      - name: Install Ninja
        run: |
          cd skia
          mkdir -p third_party/externals/ninja
          curl -L https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip -o ninja.zip
          unzip ninja.zip -d third_party/externals/ninja
          cp third_party/externals/ninja/ninja.exe C:/Windows/System32/

      - name: Install HarfBuzz
        run: |
          cd skia
          curl -L https://github.com/harfbuzz/harfbuzz/releases/download/2.8.1/harfbuzz-2.8.1-win64.zip -o harfbuzz.zip
          unzip harfbuzz.zip -d third_party/externals/harfbuzz
          cp third_party/externals/harfbuzz/include/hb.h third_party/externals/harfbuzz/include/

      - name: Build Skia with GN and Ninja
        run: |
          cd skia
          bin/gn gen out/Release --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false"
          ninja -C out/Release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: skia-dll
          path: skia/out/Release/skia.dll

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: skia-dll
          path: skia/out/Release/skia.dll
          if-no-files-found: error

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: skia/out/Release/skia.dll
        env:
          GITHUB_TOKEN: ${{ secrets.tk }}
